export const ADD_NOTES = 'ADD_NOTES'
export const REMOVE_NOTES = 'REMOVE_NOTES'
export const SET_NOTES = 'SET_NOTES'
export const INIT_NOTES = 'INIT_NOTES'

export const FETCH_NOTES_INIT = 'FETCH_NOTES_INIT'
export const FETCH_NOTES_START = 'FETCH_NOTES_START'
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS'
export const FETCH_NOTES_FAILED = 'FETCH_NOTES_FAILED'
